apiVersion: v1
name: hubble
version: 0.5.2
appVersion: 0.5.2
tillerVersion: ">=2.7.2"
description: Helm chart for the Hubble server
keywords:
sources:
  - https://github.com/cilium/hubble
engine: gotpl
