version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "vendor:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    ignore:
      - dependency-name: "github.com/cilium/cilium"
    labels:
    - kind/enhancement
    - release-note/misc
    - priority/release-blocker
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    labels:
    - kind/enhancement
    - release-note/misc
    - priority/release-blocker
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "dockerfile:"
    open-pull-requests-limit: 5
    rebase-strategy: disabled
    labels:
    - kind/enhancement
    - release-note/misc
    - priority/release-blocker
