version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "vendor:"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
      - dependency-name: "github.com/cilium/cilium"
    labels:
    - kind/enhancement
    - release-note/misc
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci:"
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
    - kind/enhancement
    - release-note/misc
