version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
    - kind/enhancement
    - release-note/misc
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
    - kind/enhancement
    - release-note/misc
