# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/master/.golangci.yaml as a
# reference.
run:
  timeout: 3m  # default is 1m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - deadcode
    - decorder
    - durationcheck
    - errchkjson
    - errname
    - gocritic
    - goerr113
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - tenv
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varcheck
    - wastedassign

linters-settings:
  gosimple:
    go: "1.18"
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  staticcheck:
    go: "1.19"
  stylecheck:
    go: "1.19"
  unused:
    go: "1.19"

issues:
  # Default rules exclude Go doc comments check, which is rather unfortunate.
  # In order to enable Go doc checks, defaults rules have to be disabled.
  # See https://github.com/golangci/golangci-lint/issues/456 for details.
  exclude-use-default: false
  exclude:
    - (G104|G307) # EXC0008 gosec: Duplicated errcheck checks

  exclude-rules:
    - linters: [staticcheck]
      text: "SA1019" # deprecated methods
    - linters: [goerr113]
      text: "do not define dynamic errors, use wrapped static errors instead"
    - linters: [gosec]
      text: "G402" # TLS InsecureSkipVerify may be true
