# See https://golangci-lint.run/usage/configuration/ for available options.
# Also https://github.com/cilium/cilium/blob/main/.golangci.yaml as a
# reference.
run:
  go: '1.21'
  timeout: 5m  # default is 1m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - gocheckcompilerdirectives
    - gocritic
    - goerr113
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nosprintfhostport
    - predeclared
    - protogetter
    - reassign
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - tenv
    - testifylint
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign

linters-settings:
  goheader:
    values:
      regexp:
        PROJECT: 'Cilium|Hubble'
    template: |-
      SPDX-License-Identifier: Apache-2.0
      Copyright Authors of {{ PROJECT }}
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  importas:
    no-unaliased: true
    alias:
      - pkg: github.com/cilium/cilium/api/v1/flow
        alias: flowpb
      - pkg: github.com/cilium/cilium/api/v1/observer
        alias: observerpb
      - pkg: github.com/cilium/cilium/api/v1/relay
        alias: relaypb
  revive:
    rules:
      - name: package-comments
        disabled: true
issues:
  # Default rules exclude Go doc comments check, which is rather unfortunate.
  # In order to enable Go doc checks, defaults rules have to be disabled.
  # See https://github.com/golangci/golangci-lint/issues/456 for details.
  exclude-use-default: false
  exclude:
    - (G104|G307) # EXC0008 gosec: Duplicated errcheck checks

  exclude-rules:
    - linters: [staticcheck]
      text: "SA1019" # deprecated methods
    - linters: [goerr113]
      text: "do not define dynamic errors, use wrapped static errors instead"
    - linters: [gosec]
      text: "G402" # TLS InsecureSkipVerify may be true
    - linters: [gosec]
      text: "G101" # Potential hardcoded credentials
    - linters: [dupword]
      path: cmd/list/node_test.go # tripping on command output
    - linters: [dupword]
      path: pkg/printer/printer_test.go # tripping on command output
