---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble
  namespace: {{ .Release.Namespace }}
{{- if .Values.ui.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: hubble-ui
{{- end }}
