{{- if and .Values.metrics.enabled (.Values.metrics.serviceMonitor.enabled) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: hubble-metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 10s
    honorLabels: true
    path: /metrics
{{- end }}
